[package]
authors = ["Kornel <pornel@pornel.net>"]
build = "build.rs"
description = "Reading and writing PNG files without system dependencies. Wrapper for lodepng."
documentation = "https://pornel.github.io/lodepng-rust/lodepng/"
homepage = "https://github.com/pornel/lodepng-rust#readme"
keywords = ["PNG","lodepng","encoder","decoder"]
license = "BSD-2-Clause"
include = ["src/**/*", "vendor/**/*", "examples/**/*", "tests/**/*", "build.rs", "Makefile", "COPYRIGHT", "README.md", "Cargo.toml"]
name = "lodepng"
readme = "README.md"
repository = "https://github.com/pornel/lodepng-rust.git"
categories = [ "multimedia::encoding", "multimedia::images", "external-ffi-bindings" ]
version = "1.2.0"

[build-dependencies]
cc = "1.0.0"

[dependencies]
c_vec = "1.3.0"
libc = "0.2.30"
rgb = "0.7.2"

[[example]]
name = "read"

[[example]]
name = "write"

[[example]]
name = "passthrough"

[[example]]
name = "read_advanced"
