[package]

name = "lodepng"
description = "Reading and writing PNG files without external dependencies. Wrapper for lodepng."
documentation = "http://pornel.github.io/lodepng-rust/lodepng/"
homepage = "https://github.com/pornel/lodepng-rust#readme"
repository = "https://github.com/pornel/lodepng-rust.git"
readme = "README.md"
keywords = ["PNG","lodepng","encoder","decoder"]
license = "BSD-2-Clause"
version = "0.4.2"
authors = [ "Kornel <pornel@pornel.net>" ]
build = "build.rs"

[dependencies]
libc = "0.1.8"
c_vec = "1.0.12"

[[example]]
name = "read"

[[example]]
name = "write"

[[example]]
name = "passthrough"
