[package]
authors = ["Kornel <kornel@geekhood.net>", "Lode Vandevenne <lvandeve@gmail.com>"]
categories = ["multimedia::encoding", "multimedia::images"]
description = "Reading and writing PNG files without system dependencies. Pure Rust port of LodePNG."
documentation = "https://pornel.github.io/lodepng-rust/lodepng/"
homepage = "https://github.com/pornel/lodepng-rust#readme"
include = ["src/**/*", "examples/**/*", "tests/**/*", "COPYRIGHT", "README.md", "Cargo.toml"]
keywords = ["PNG","lodepng","encoder","decoder"]
license = "BSD-3-Clause"
name = "lodepng"
readme = "README.md"
repository = "https://github.com/pornel/lodepng-rust.git"
version = "2.0.4"

[dependencies]
libc = "0.2.33"
rgb = "0.8"

[dev-dependencies]
lodepng_unittest = { path="lodepng_unittest" }

[[example]]
name = "read"

[[example]]
name = "write"

[[example]]
name = "passthrough"

[[example]]
name = "read_advanced"

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 2

[features]
c_statics = []
