[package]
authors = ["Kornel <kornel@geekhood.net>", "Lode Vandevenne <lvandeve@gmail.com>"]
categories = ["multimedia::encoding", "multimedia::images"]
description = "Reading and writing PNG files without system dependencies. Pure Rust port of LodePNG."
documentation = "https://docs.rs/lodepng"
homepage = "https://lib.rs/crates/lodepng"
include = ["src/**/*", "COPYRIGHT", "README.md", "Cargo.toml"]
keywords = ["PNG","lodepng","encoder","decoder"]
license = "BSD-3-Clause"
name = "lodepng"
readme = "README.md"
repository = "https://github.com/kornelski/lodepng-rust.git"
version = "2.7.1"
edition = "2018"

[badges]
travis-ci = { repository = "kornelski/lodepng-rust" }

[dependencies]
libc = "0.2.69"
rgb = "0.8.17"

[workspace]
members = ["lodepng_unittest"]

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 2

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
