[package]

name = "lodepng"
description = "Reading and writing PNG files without external dependencies. Wrapper for lodepng."
documentation = "http://pornel.github.io/lodepng-rust/lodepng/"
homepage = "https://github.com/pornel/lodepng-rust#readme"
repository = "https://github.com/pornel/lodepng-rust.git"
readme = "README.md"
keywords = ["PNG","lodepng","encoder","decoder","gzip","deflate"]
license = "BSD-2-Clause"
version = "0.2.1"
authors = [ "pornel@pornel.net" ]
build = "sh build.sh"

[[example]]
name = "read"

[[example]]
name = "write"

[[example]]
name = "passthrough"
