[package]

name = "lodepng"
description = "Reading and writing PNG files without external dependencies. Wrapper for lodepng."
documentation = "http://pornel.github.io/lodepng-rust/lodepng/"
homepage = "https://github.com/pornel/lodepng-rust#readme"
repository = "https://github.com/pornel/lodepng-rust.git"
readme = "README.md"
keywords = ["PNG","lodepng","encoder","decoder"]
license = "BSD-2-Clause"
authors = [ "Kornel <pornel@pornel.net>" ]
build = "build.rs"
include = ["src/**/*", "examples/**/*", "build.rs", "Makefile", "COPYRIGHT", "README.md", "Cargo.toml"]
version = "0.6.2"

[dependencies]
libc = "0.2.0"
c_vec = "= 1.0.12"
rgb = "0.2.0"

[[example]]
name = "read"

[[example]]
name = "write"

[[example]]
name = "passthrough"
